version: "3.8"
services:
  app:
    image: playground-app
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    ports:
      - "8081:8081"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/code
